config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  
  resources :pins do
    member do
      put "like", to: "pins#upvote"
    end
  end

  root "pins#index"

end

app/models/pin.rb
class Pin < ActiveRecord::Base
  belongs_to :user
  acts_as_votable
  
  # has_attached_file :image, styles: { medium: "300x300>" }
  # validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/

  # default_scope { order('votes_for DESC') }

  #uploader
  attr_accessor :photo
  mount_uploader :photo, PhotoUploader

  acts_as_ordered_taggable_on :category
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :pins
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  before_action :configure_permitted_parameters, if: :devise_controller?
  protected
  
  # def configure_permitted_parameters
  #   added_attrs = [ :username, :email, :password, :password_confirmation　]
  #   devise_parameter_sanitizer.for :sign_up, keys: added_attrs
  #   devise_parameter_sanitizer.for :account_update, keys: added_attrs
  #   devise_parameter_sanitizer.for :sign_in,keys: added_attrs
  # end
  
  
  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :username
    devise_parameter_sanitizer.for(:account_update) << :username
  end
end

app/controllers/pins_controller.rb
class PinsController < ApplicationController
  before_action :find_pin, only: [:show, :edit, :update, :destroy, :upvote]
  before_action :authenticate_user!,  except: [:index, :show]
  
	def index
		@pins = Pin.all.order("created_at DESC")
	end

	def show
	end

	def new
		@pin = current_user.pins.build
	end

	def create
		@pin = current_user.pins.build(pin_params)
	  if @pin.save
			redirect_to @pin, notice: "Pin was successfully created"
		else
			render 'new'
		end
	end

	def edit
	end

	def update
		if @pin.update(pin_params)
			redirect_to @pin, notice: "Pin was successfully updated"
		else
			render 'edit'
		end
	end

	def destroy
		@pin.destroy
		redirect_to root_path
	end
	
	def upvote
		@pin.upvote_by current_user
		redirect_to :back
	end

	def pin_params
		params.require(:pin).permit(:title, :description, :image, :category_list, :photo)
	end

	def find_pin
		@pin = Pin.find(params[:id])
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pins_helper.rb
module PinsHelper
end

app/views/layouts/application.html.haml
!!! 5
%html
%head
  %title Awesome Photo
  = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
  = javascript_include_tag 'application', 'data-turbolinks-track' => true
  = csrf_meta_tags
%body
  %nav.navbar.navbar-default
    .container
      .navbar-brand= link_to "Awesome Photo", root_path
      
      -if user_signed_in?
        %ul.nav.navbar-nav.navbar-right
          %li
            = link_to new_pin_path do
              %i.fa.fa-plus
              
          %li
            = link_to edit_user_registration_path do
              %i.fa.fa-cog
              
          %li= link_to "SignOut", destroy_user_session_path, method: :delete
      -else
        %ul.nav.navbar-nav.navbar-right
          %li= link_to "SignUp", new_user_registration_path
          %li= link_to "SignIn", new_user_session_path
      
  .container
    - flash.each do |name, msg|
      = content_tag :div, msg, class: "alert alert-info"
    = yield

app/views/pins/_form.html.haml
= simple_form_for @pin, html: { multipart: true } do |f|
	- if @pin.errors.any?
		#errors
			%h2
				= pluralize(@pin.errors.count, "error")
				prevented this Pin from saving
			%ul
				- @pin.errors.full_messages.each do |msg|
					%li= msg
					
					
	
	.preview
	
	.form-group
		= f.input :photo, input_html: { class: 'form-control', type: 'file' }
	
	.form-group
		= f.input :title, input_html: { class: 'form-control' }
	
	.form-group
		= f.input :description, input_html: { class: 'form-control' }
		
	.form-group
		= f.label :category_list, input_html: { class: 'form-control' }
		= text_field_tag 'pin[category_list]', @pin.category_list.join('.')

	= f.button :submit, class: "btn btn-primary"

app/views/pins/edit.html.haml
#edit_page.col-md-8.col-md-offset-2
	.row
		.panel.panel-default
			.panel-heading
				%h1 Edit Your Pin
			.panel-body
				.current_image
					%strong.center Current Image
					= image_tag @pin.photo.url(:medium)
				= render 'form'

app/views/pins/index.html.haml
#pins.transitions-enabled
	- @pins.each do |pin|
		.box.panel.panel-default
			= link_to (image_tag pin.photo.url), pin
			%h2= link_to pin.title, pin
			%p.user
				Submitted by
			//	= @pin.user.username

app/views/pins/new.html.haml
.col-md-8.col-md-offset-2
	.row
		.panel.panel-default
			.panel-heading
				%h1 Create A New Pin
			.panel-body
				= render 'form'

app/views/pins/show.html.haml
#pin_show.row
  .col-md-8.col-md-offset-2
    .panel.panel-default
      .panel-heading.pin_image
        = image_tag @pin.photo.url()
      .panel-body
        %h1= @pin.title
        %p= @pin.description
        // - @pin.category_list.each do |post|
        //   = post
        
        -@pin.category_list.each do |tags|
          #div.tag
            = tags
      .panel-footer
        .row
          .col-md-6
            %p.user
            Submitted by
            = @pin.user.username
          .col-md-6
            .btn-group.pull-right
              = link_to like_pin_path(@pin), method: :put, class: "btn btn-default" do
                %span.glyphicon.glyphicon-heart
                  = @pin.get_upvotes.size
              - if user_signed_in?   
                = link_to "edit", edit_pin_path, class: "btn btn-default"
                = link_to "delete", pin_path, method: :delete, data: { confirm: "Are you sure?" },class: "btn btn-default"